import type { Metadata } from "next";
import { inter } from "./font";
import "./globals.css";
import { AppProvider } from "@/context/AppContext";
import Nav from "@/components/Nav/Nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
